CREATE TABLE users
(
    id       BIGINT PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY,
    name     text NOT NULL,
    email    text NOT NULL,
    password text NOT NULL,
    image    bytea,
    UNIQUE (name)
);

CREATE TABLE chats
(
    id          BIGINT PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY,
    first_user  BIGINT NOT NULL,
    second_user BIGINT NOT NULL,
    FOREIGN KEY (first_user) REFERENCES users (id) ON DELETE CASCADE,
    FOREIGN KEY (second_user) REFERENCES users (id) ON DELETE CASCADE,
    UNIQUE (first_user, second_user)
);

CREATE TABLE channels
(
    id      BIGINT PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY,
    creator BIGINT NOT NULL,
    name    text   NOT NULL,
    FOREIGN KEY (creator) REFERENCES users (id) ON DELETE CASCADE,
    UNIQUE (creator, name)
);


CREATE TABLE messages
(
    id      BIGINT PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY,
    sender  BIGINT NOT NULL,
    chat    BIGINT,
    channel BIGINT,
    data    text   NOT NULL,
    FOREIGN KEY (sender) REFERENCES users (id) ON DELETE CASCADE,
    FOREIGN KEY (chat) REFERENCES chats (id) ON DELETE CASCADE,
    FOREIGN KEY (channel) REFERENCES channels (id) ON DELETE CASCADE
);

CREATE TABLE members
(
    id         BIGINT PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY,
    channel_id BIGINT NOT NULL,
    user_id    BIGINT NOT NULL,
    FOREIGN KEY (user_id) REFERENCES users (id) ON DELETE CASCADE,
    FOREIGN KEY (channel_id) REFERENCES channels (id) ON DELETE CASCADE,
    UNIQUE (user_id, channel_id)
);

CREATE TABLE roles
(
    id         BIGINT PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY,
    member     BIGINT NOT NULL,
    name       text   NOT NULL,
    is_admin   bool   NOT NULL default false,
    is_creator bool   NOT NULL default false,
    FOREIGN KEY (member) REFERENCES members (id) ON DELETE CASCADE,
    UNIQUE (member)
);

CREATE TABLE saved_messages
(
    id         BIGINT PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY,
    message_id BIGINT NOT NULL,
    user_id    BIGINT NOT NULL,
    FOREIGN KEY (user_id) REFERENCES users (id) ON DELETE CASCADE,
    FOREIGN KEY (message_id) REFERENCES messages (id) ON DELETE CASCADE,
    UNIQUE (user_id, message_id)
)