import { StyleSheet, useWindowDimensions } from 'react-native-web';

export default function useStyles() {

  const { width, height } = useWindowDimensions();

  return StyleSheet.create({
    container: {
      flex: 1,
      backgroundColor: '#FFFFFF',
      justifyContent: 'center',
      alignItems: 'center',
    },
    headerButton: {
      marginTop: 30, 
    },
    channNameContainer: {
      flexDirection: 'row',
      justifyContent: 'center',
      alignItems: 'center',
      top: 80,
      paddingLeft: 10,
      overflow: 'hidden',
      position: 'absolute',
    },
    dataInputContainer: {
      marginRight: 10,
    },
    nicknameContainer: {
      flexDirection: 'row',
      alignItems: 'center',
      marginBottom: 13,
    },
    containerMain: {
      flex: 1,
      backgroundColor: 'rgba(0, 118, 185, 0.35)',
      justifyContent: 'center',
      alignItems: 'center',
    },
    containerSettings: {
      flex: 1,
      justifyContent: 'center',
      flexDirection: "row",
      alignItems: 'center',
      backgroundColor: 'rgba(0, 118, 185, 0.35)',
    },
    bottomLeft: {
      position: 'absolute',
      bottom: 20,
      left: 20,
    },
    topLeft: {
      position: 'absolute',
      top: 20,
      left: 20,
    },
    textContainer: {
      backgroundColor: '#FFFFFF',
      borderRadius: 35,
      padding: 30,
      shadowColor: '#000',
      shadowOffset: { width: 2, height: 2 },
      shadowOpacity: 0.25,
      shadowRadius: 3.84,
      elevation: 7,
      position: 'absolute',
      top: '30%',
      alignSelf: 'auto',
      alignItems: 'center',
      justifyContent: 'center',
    },
    messageContainer: {
      backgroundColor: '#FFFFFF',
      padding: 2,
      borderRadius: 35,
      marginBottom: 10,
      width: '27%',
      height: '80%',
      overflow: 'hidden',
      position: 'absolute',
      top: Math.min(width * 0.25, height * 0.07),
      right: Math.min(width * 0.4, height * 0.9),
      shadowColor: '#000',
      shadowOffset: { width: 2, height: 2 },
      shadowOpacity: 0.25,
      shadowRadius: 3.84,
      elevation: 7,
    },
    barContainer: {
      backgroundColor: '#FFFFFF',
      borderRadius: 35,
      width: '50%',
      //height: '10%',
      overflow: 'hidden',
      position: 'absolute',
      top: 40, 
      right: 80, 
      shadowColor: '#000',
      shadowOffset: { width: 2, height: 2 },
      shadowOpacity: 0.25,
      shadowRadius: 3.84,
      elevation: 7,
    },
    barChanContainer: {
      backgroundColor: '#FFFFFF',
      borderRadius: 35,
      width: '50%',
      //height: '10%',
      overflow: 'hidden',
      position: 'absolute',
      top: 40,
      right: 80,
      shadowColor: '#000',
      shadowOffset: { width: 2, height: 2 },
      shadowOpacity: 0.25,
      shadowRadius: 3.84,
      elevation: 7,
      flexDirection: 'row',
      justifyContent: 'space-between',
      alignItems: 'center',
    },
    barText: {
      fontFamily: 'Montserrat-Regular',
      fontSize: Math.min(width * 0.012, height * 0.032),
      paddingLeft: 20,
    },
    settingsContainer: {
      alignItems: 'center',
      flex: 1,
      backgroundColor: '#FFFFFF',
      borderRadius: 35,
      padding: 20,
      shadowColor: '#000',
      shadowOffset: { width: 2, height: 2 },
      shadowOpacity: 0.25,
      shadowRadius: 3.84,
      elevation: 7,
      backgroundColor: '#FFFFFF',
      borderRadius: 35,
      width: '30%',
      height: '40%',
      overflow: 'hidden',
      position: 'absolute',
      
    },
    sendContainer: {
      width: width * 0.4,
      height: height * 0.1,
      position: 'absolute',
      bottom: 0,
      right: width * 0.073,
      marginTop: 50
    },
    forwardContainer: {
      backgroundColor: '#FFFFFF',
      padding: 10,
      borderRadius: 25,
      width: '30%',
      height: '81%',
      overflow: 'hidden',
      position: 'absolute',
      bottom: Math.min(width * 0.05, height * 0.15),
      right: Math.min(width * 0.008, height * 0.09),
      shadowColor: '#000',
      shadowOffset: { width: 2, height: 2 },
      shadowOpacity: 0.25,
      shadowRadius: 3.84,
      elevation: 7,
    },
    containerTop: {
      borderBottomWidth: 1,
      borderBottomColor: 'gray',
      paddingHorizontal: 16,
      paddingTop: 4,
      paddingBottom: 5,
    },
    containerBottom: {
      borderTopWidth: 1,
      borderColor: 'gray',
      borderBottomWidth: 1,
      paddingHorizontal: 16,
      paddingTop: 4,
      paddingBottom: 5,
    },
    emptyContainer: {
      flex: 1,
      justifyContent: 'center',
      alignItems: 'center',
      paddingHorizontal: 16,
      paddingVertical: 15,
    },
    
    historyContainer: {
      backgroundColor: '#FFFFFF',
      padding: 10,
      borderRadius: 15,
      marginTop: 30,
      width: '35%',
      height: '70%',
      overflow: 'hidden',
      position: 'absolute',
      top: '50%', 
      right: width * 0.1,
      transform: [{ translateY: '-50%' }], 
      shadowColor: '#000',
      shadowOffset: { width: 2, height: 2 },
      shadowOpacity: 0.25,
      shadowRadius: 3.84,
      elevation: 7,
    },
    headerBar: {
      flexDirection: 'row',
      alignItems: 'center',
      justifyContent: 'space-between',
      paddingHorizontal: 16,
      paddingBottom: 10,
      marginBottom: 13,
      borderBottomWidth: 1,
      borderBottomColor: 'black',
    },
    headerText: {
      fontSize: Math.min(width * 0.012, height * 0.032),
      fontFamily: 'Montserrat-Regular',
    },
    emptyMessageContainer: {
      top: Math.min(width * 0.15, height * 0.3),
      justifyContent: 'center',
      alignItems: 'center',
    },
    emptyMessageText: {
      fontSize: Math.min(width * 0.012, height * 0.032),
      fontFamily: 'Montserrat-Regular',
      color: 'gray',
    },
    profileContainer: {
      backgroundColor: '#FFFFFF',
      borderRadius: 35,
      width: width * 0.2,
      height: height*0.5,
      overflow: 'hidden',
      position: 'absolute',
      top: 40, 
      left: 80, 
      shadowColor: '#000',
      shadowOffset: { width: 2, height: 2 },
      shadowOpacity: 0.25,
      shadowRadius: 3.84,
      elevation: 7,
      alignItems: 'center',
      justifyContent: 'center',
     paddingVertical: 60
    },
    profileSettingsContainer: {
      backgroundColor: '#FFFFFF',
      borderRadius: 35,
      width: width * 0.24,
      height: height *0.68,
      overflow: 'hidden',
      position: 'absolute',
      shadowColor: '#000',
      shadowOffset: { width: 2, height: 2 },
      shadowOpacity: 0.25,
      shadowRadius: 3.84,
      elevation: 7,
      alignItems: 'center',
      justifyContent: 'center',
      paddingTop: 30,
      paddingBottom: 30,
      alignSelf: 'stretch',
      marginTop: 'auto',
      marginBottom: 'auto',
      left: '50%',
      top: '50%',
      transform: [{ translateX: '-50%' }, { translateY: '-50%' }],
    },


    popupContainer: {
      backgroundColor: '#E7DEDE',
      borderRadius: 35,
      padding: 20,
      shadowColor: '#000',
      shadowOffset: { width: 2, height: 2 },
      shadowOpacity: 0.25,
      shadowRadius: 3.84,
      elevation: 7,
      position: 'absolute',
      top: '50%', 
      left: '50%', 
      transform: [{ translateX: '-50%' }, { translateY: '-50%' }], 
      width: '20%',
      height: '20%',
      justifyContent: 'center',
      alignItems: 'center',
      flexDirection: 'column',
    },
    text: {
      fontFamily: 'Montserrat-Regular',
      color: '#000000',
      fontSize: Math.min(width * 0.012, height * 0.032),
      textAlign: 'center',
      marginBottom: 13
    },
    inputContainer: {
      width: '80%',
      alignItems: 'center',
      justifyContent: 'flex-start',
      paddingTop: 20
    },
  });
}